services:
  sonarr:
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=${UMASK}
    expose:
      - 8989
    image: lscr.io/linuxserver/sonarr:latest
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.sonarr.rule=Host(`sonarr.${DOMAIN}`)'
      - 'traefik.http.routers.sonarr.tls=true'
    networks:
      - default
    restart: always
    volumes:
      - '${PROJECT_ROOT}/config/sonarr:/config'
      - '${PROJECT_ROOT}/data/downloads:/downloads'
      - '${PROJECT_ROOT}/data/share/tv:/tv'
