services:
  rdtclient:
    container_name: rdtclient
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=${UMASK}
    expose:
      - 6500
    image: rogerfar/rdtclient
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.rdtclient.rule=Host(`rdtclient.${DOMAIN}`)'
      - 'traefik.http.routers.rdtclient.tls=true'
    logging:
      driver: json-file
      options:
        max-size: 10m
    networks:
      - default
    restart: always
    volumes:
      - '${INSTALL_DIR}/config/rdtclient:/config'
      - '${INSTALL_DIR}/data/rdtclient:/data/db'
      - '${DOWNLOADS_DIR}:/data/downloads'
      - '${INSTALL_DIR}/data/tmp:/data/tmp'
