global:
  checkNewVersion: false
  sendAnonymousUsage: false

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: :443

log: {}

api:
  insecure: false
  dashboard: true

providers:
  docker:
    defaultRule: Host(`{{ normalize .Name }}.${DOMAIN}`)
    exposedByDefault: false
    network: traefik

  file:
    directory: '/etc/traefik/dynamic'
    watch: true
