services:
  watchtower:
    container_name: watchtower
    environment:
      - TZ=${TZ}
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_HTTP_API_METRICS=true
      - WATCHTOWER_HTTP_API_TOKEN=${WATCHTOWER_API_TOKEN}
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_NOTIFICATIONS=shoutrrr
      - WATCHTOWER_NOTIFICATIONS_HOSTNAME=${PROJECT_NAME}
      - WATCHTOWER_NOTIFICATION_URL=${WATCHTOWER_NOTIFICATION_URL}
      - WATCHTOWER_ROLLING_RESTART=true
      - WATCHTOWER_SCHEDULE=${WATCHTOWER_SCHEDULE}
    expose:
      - 8080
    image: containrrr/watchtower
    networks:
      - default
    restart: always
    volumes:
      - '${DOCKER_SOCKET}:/var/run/docker.sock:ro'
