---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/services/

- System:
    #pihole
    - Pi Hole:
        icon: pihole.png
        href: https://pihole.${DOMAIN}/
        description: Pi Hole
        server: docker
        container: pihole
        widget:
          type: pihole
          url: http://pihole
    #traefik
    - Traefik:
        icon: traefik.png
        href: https://traefik.${DOMAIN}
        description: Traefik
        server: docker
        container: traefik
        widget:
          type: traefik
          url: https://traefik.${DOMAIN}
    #portainer
    - Portainer:
        icon: portainer.png
        href: https://portainer.${DOMAIN}
        description: Portainer
        widget:
          type: portainer
          url: http://portainer:9000
          env: 1
          key: '${PORTAINER_ACCESS_TOKEN}'
    #watchtower
    - Watch Tower:
        icon: watchtower.png
        description: Watch Tower
        server: docker
        container: watchtower
        widget:
          type: watchtower
          url: http://watchtower:8080
          key: '${WATCHTOWER_API_TOKEN}'
    #dozzle
    - Dozzle:
        icon: dozzle.png
        href: https://dozzle.${DOMAIN}
        description: Dozzle
        server: docker
        container: dozzle
    #
- Multimedia:
    #radarr
    - Radarr:
        icon: radarr.png
        href: https://radarr.${DOMAIN}
        description: Radarr
        server: docker
        container: radarr
        widget:
          type: radarr
          url: http://radarr:7878
          key: '${RADARR_API_KEY}'
    #sonarr
    - Sonarr:
        icon: sonarr.png
        href: https://sonarr.${DOMAIN}
        description: Sonarr
        server: docker
        container: sonarr
        widget:
          type: sonarr
          url: http://sonarr:8989
          key: '${SONARR_API_KEY}'
    #lidarr
    - Lidarr:
        icon: lidarr.png
        href: https://lidarr.${DOMAIN}
        description: Lidarr
        server: docker
        container: lidarr
        widget:
          type: lidarr
          url: http://lidarr:8686
          key: '${LIDARR_API_KEY}'
    #bazarr
    - Bazarr:
        icon: bazarr.png
        href: https://bazarr.${DOMAIN}
        description: Bazarr
        server: docker
        container: bazarr
        widget:
          type: bazarr
          url: http://bazarr:6767
          key: '${BAZARR_API_KEY}'
    #whisparr
    - Whisparr:
        icon: whisparr.png
        href: https://whisparr.${DOMAIN}
        description: Whisparr
        server: docker
        container: whisparr
        widget:
          type: radarr
          url: http://whisparr:6969
          key: '${WHISPARR_API_KEY}'
    #
- File Management:
    #jackett
    - Jackett:
        icon: jackett.png
        href: https://jackett.${DOMAIN}
        description: Jackett
        server: docker
        container: jackett
    #prowlarr
    - Prowlarr:
        icon: prowlarr.png
        href: https://prowlarr.${DOMAIN}
        description: Prowlarr
        server: docker
        container: prowlarr
        widget:
          type: prowlarr
          url: http://prowlarr:9696
          key: '${PROWLARR_API_KEY}'
    #rdtclient
    - RDT Client:
        icon: qbittorrent.png
        href: https://rdtclient.${DOMAIN}
        description: RDT Client
        server: docker
        container: rdtclient
        widget:
          type: qbittorrent
          url: http://rdtclient:6500
          username: '${USERNAME}'
          password: '${PASSWORD}'
    #filebrowser
    - Filebrowser:
        icon: filebrowser.png
        href: https://filebrowser.${DOMAIN}
        description: File Browser
        server: docker
        container: filebrowser
