---
# For configuration options and examples, please see:
# https://github.com/benphelps/homepage/wiki/Information-Widgets

- resources:
    cpu: true
    memory: true
    disk: /

- search:
    provider: duckduckgo
    target: _blank

- openweathermap:
    label: ${OPENWEATHERMAP_LABEL}
    latitude: ${OPENWEATHERMAP_LAT}
    longitude: ${OPENWEATHERMAP_LNG}
    units: ${OPENWEATHERMAP_UNITS}
    provider: openweathermap
    cache: 5
